openapi: 3.0.0
info:
  description: API description for the rideshare backend.
  version: "1.0.0-oas3"
  title: Rideshare
  contact:
    email: quan@mqt.io
tags:
  - name: user
    description: User operations
  - name: ride
    description: Ride operations
paths:
  /user:
    get:
      tags:
        - user
      summary: Get list of all users
      description: This is only accessible by an administrator.
      operationId: getAllUsers
      responses:
        '200':
          description: Successful fetch operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '500':
          description: Internal server error
    post:
      tags:
        - user
      summary: Create user
      description: This is the endpoint for signing up users.
      operationId: createUser
      responses:
        '201':
          description: User successfully created
        '400':
          description: Bad parameter in request body
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
    delete:
      tags:
        - user
      summary: Delete all users
      description: >-
        This is a testing endpoint not meant for production. This is only
        accessible by an administrator
      operationId: deleteAllUsers
      responses:
        '200':
          description: Users successfully deleted
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '500':
          description: Internal server error
  '/user/{id}':
    get:
      tags:
        - user
      summary: Get user by ID
      description: >-
        This is only accessible by an authenticated user with the given ID or an
        administrator.
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: The ID of the user to fetch.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful fetch operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid user ID supplied
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tags:
                      type: string
                      example: invalidId
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '404':
          description: User not found
        '500':
          description: Internal server error
    put:
      tags:
        - user
      summary: Update user information
      description: This is only accessible by a authenticated user with the given ID.
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: id of user to be updated
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User successfully updated
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tags:
                      type: string
                      example: badValue
                    params:
                      type: array
                      items:
                        type: string
                        example: email
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '404':
          description: User not found
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
    delete:
      tags:
        - user
      summary: Delete user
      description: >-
        This is only accessible by an authenticated user with the given ID or an
        administrator.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: id of user to be deleted
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User successfully deleted
        '400':
          description: Invalid user ID supplied
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tags:
                      type: string
                      example: invalidId
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '404':
          description: User not found
        '500':
          description: Internal server error
servers:
  - url: 'http://localhost:5000/'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique user ID.
          example: 1
        firstName:
          type: string
          description: User's given name.
          example: Joe
        lastName:
          type: string
          description: User's family name.
          example: Emenaker
        email:
          type: string
          description: Unique user email.
          example: jemenake@calpoly.edu
        password:
          type: string
          format: password
          description: User's password (ignore this security risk for now..).
          example: S3CR3Tp4ssw0rd
      xml:
        name: User
    Ride:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ride ID.
          example: 7
        from:
          type: string
          description: Ride start location.
          example: San Luis Obispo
        to:
          type: string
          description: Ride destination.
          example: San Diego
        date:
          type: object
          description: Expected departure time range.
          properties:
            description:
              type: string
              description: Friendly description of the time range.
              example: Early afternoon
            start_time:
              type: integer
              format: int32
              description: Start time of the time range.
              example: 12
            end_time:
              type: integer
              format: int32
              description: End time of the time range.
              example: 15
        actual_time:
          type: string
          format: date-time
          description: Actual ride departure time.
          example: '2018-10-01T13:30:00.000'
        capacity:
          type: integer
          description: Number of total passenger seats offered by the ride.
          example: 3
        driver:
          type: object
          description: User offering the ride.
          properties:
            id:
              type: integer
              format: int64
              description: Unique user ID.
              example: 1
            firstName:
              type: string
              description: User's given name.
              example: Joe
            lastName:
              type: string
              description: User's family name.
              example: Emenaker
        passengers:
          type: array
          items:
            type: object
            description: User interested in the ride.
            properties:
              id:
                type: integer
                format: int64
                description: Unique user ID.
                example: 2
              firstName:
                type: string
                description: User's given name.
                example: Kendrick
              lastName:
                type: string
                description: User's family name.
                example: Lamar
              status:
                type: string
                description: >-
                  Passenger status for the ride. e.g. 'REQUESTED', 'CONFIRMED',
                  'CANCELLED'
                example: CONFIRMED
      xml:
        name: Ride
    Error:
      type: object
      properties:
        tags:
          type: string
          example: missingField
        params:
          type: array
          items:
            type: string
            example: email
      xml:
        name: Error